repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix']

  - repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.52.11
    hooks:
      - id: swiftformat
        args: ['--config', '.swiftformat']

  - repo: local
    hooks:
      - id: swift-build
        name: Swift Build Check
        entry: bash -c 'cd macos-menubar/Simple4D && xcodebuild -project Simple4D.xcodeproj -scheme Simple4D -configuration Debug build'
        language: system
        files: '\.swift$'
        pass_filenames: false
